{% set name = "jsonnet" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cde3d079fbeecbeb80305f388cf05c7bda5fe7bdb94e6197501ce69a3cb3aa1e

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - _jsonnet

about:
  home: http://github.com/google/jsonnet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python bindings for Jsonnet - The data templating language'

extra:
  recipe-maintainers:
    - nelson-liu
