{% set name = "jsonnet" %}
{% set version = "0.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fe2865e6e1dc2b9791d880fea3eba7e72334b256d85f027da3ae1f56a55b1da
  patches:
    - patches/0001-python313-pyeval-fix.patch


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - _jsonnet

about:
  home: http://github.com/google/jsonnet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python bindings for Jsonnet - The data templating language

extra:
  recipe-maintainers:
    - nelson-liu
    - michamucha
    - synapticarbors
