{% set name = "jsonnet" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9ac8ba0b44aac85a66bf950a155ee6286f0234db162a92a3f8cd2ef7a58a9cc

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - _jsonnet

about:
  home: http://github.com/google/jsonnet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python bindings for Jsonnet - The data templating language'

extra:
  recipe-maintainers:
    - nelson-liu
